config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  # Consultar rutas: http://127.0.0.1:3000/rails/info/routes
  # Tipo de Petición    Ruta                Controlador(NombreControlador#Método)   Nombre de la Ruta (Helper)
  # get                 '/products/new',    to: 'products#new',                     as: :new_product
  # delete '/products/:id', to: 'products#destroy'
  # patch '/products/:id', to: 'products#update'
  # post '/products', to: 'products#create'
  # get '/products/new', to: 'products#new', as: :new_product
  # get '/products', to: 'products#index'
  # get '/products/:id', to: 'products#show', as: :product
  # get '/products/:id/edit', to: 'products#edit', as: :edit_product

  # Las rutas anteriores pueden ser reemplazadas por esta línea dejando como ruta raíz la página que muestra todos los productos
  # resources crea siete rutas con los verbos HTTP por defecto
  
  namespace :authentication, path: '', as: '' do
    resources :users, only: [:new, :create], path: '/register', path_names: { new: '/' }
    resources :sessions, only: [:new, :create, :destroy], path: '/login', path_names: { new: '/' }
  end

  resources :products, path: '/products'

  get '/categories', to: 'categories#index'
  delete '/categories/:id', to: 'categories#destroy'
  get '/categories/new', to: 'categories#new', as: :new_category
  post '/categories', to: 'categories#create'
  patch '/categories/:id', to: 'categories#update'
  get '/categories/:id', to: 'categories#show', as: :category
  get '/categories/:id/edit', to: 'categories#edit', as: :edit_category

  resources :users, only: :show, path: '/user', param: :username

  resources :favorites, only: [:index, :create, :destroy], param: :product_id

  end

app/views/shared/_flash.html.erb
<%= notice %>

<%= alert %>

app/views/shared/_header.html.erb
<div class="bg-white flex justify-between items-center px-2" data-controller="menu">

  <%= link_to products_path do %>
      <h1 class="text-2xl font-bold text-teal-500">Vendelo</h1>
  <% end %>

  <button class="sm:hidden" data-action="click->menu#toggle"><%= image_tag 'icons/menu.svg', width: 35, height: 35 %></button>

  <div class="hidden sm:block">
      <%= render partial: 'shared/items' %>
  </div>

  <!-- Menu Mobile -->
  <div class="gap-4 sm:hidden absolute bg-white top-0 right-0 shadow z-10 h-full flex flex-col min-w-[45%] overflow-y-scroll ease-in-out duration-200 p-5 translate-x-full" data-menu-target="items">
    <button data-action="click->menu#toggle"><%= image_tag 'icons/close.svg', width: 35, height: 35 %></button>
    <%= render partial: 'shared/items' %>
  </div>
</div>

app/views/shared/_items.html.erb
<%= link_to 'Añadir producto', new_product_path, class: "mx-2 text-teal-500 font-bold", data: { turbo_frame: "modal" } if Current.user %>
<%= link_to 'Mis Favoritos', favorites_path, class: "mx-2 text-teal-500 font-bold" if Current.user %>
<%= link_to 'Categorías', categories_path, class: "mx-2 text-teal-500 font-bold" if Current.user&.admin? %>
<%= link_to 'Login', new_session_path, class: "mx-2 text-teal-500 font-bold" unless Current.user %>
<%= link_to 'Sign Up', new_user_path, class: "mx-2 text-teal-500 font-bold" unless Current.user %>
<%= link_to 'Log Out', session_path(Current.user.id), data: {
  turbo_method: :delete,
  turbo_confirm: 'Are you sure?'
}, class: "mx-2 text-teal-500 font-bold" if Current.user %>