config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  # Consultar rutas: http://127.0.0.1:3000/rails/info/routes
  # Tipo de Petición    Ruta                Controlador(NombreControlador#Método)   Nombre de la Ruta (Helper)
  # get                 '/products/new',    to: 'products#new',                     as: :new_product
  # delete '/products/:id', to: 'products#destroy'
  # patch '/products/:id', to: 'products#update'
  # post '/products', to: 'products#create'
  # get '/products/new', to: 'products#new', as: :new_product
  # get '/products', to: 'products#index'
  # get '/products/:id', to: 'products#show', as: :product
  # get '/products/:id/edit', to: 'products#edit', as: :edit_product

  # Las rutas anteriores pueden ser reemplazadas por esta línea dejando como ruta raíz la página que muestra todos los productos
  # resources crea siete rutas con los verbos HTTP por defecto
  
  namespace :authentication, path: '', as: '' do
    resources :users, only: [:new, :create], path: '/register', path_names: { new: '/' }
    resources :sessions, only: [:new, :create, :destroy], path: '/login', path_names: { new: '/' }
  end

  resources :products, path: '/products'

  get '/categories', to: 'categories#index'
  delete '/categories/:id', to: 'categories#destroy'
  get '/categories/new', to: 'categories#new', as: :new_category
  post '/categories', to: 'categories#create'
  patch '/categories/:id', to: 'categories#update'
  get '/categories/:id', to: 'categories#show', as: :category
  get '/categories/:id/edit', to: 'categories#edit', as: :edit_category

  resources :users, only: :show, path: '/user', param: :username

  resources :favorites, only: [:index, :create, :destroy], param: :product_id

  end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
  has_many :products, dependent: :restrict_with_exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :authorize!

  def index
    @categories = Category.all.order(name: :asc)
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path
    else
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to categories_path
    else
      render :edit
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path, status: :see_other
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end

end

app/views/categories/_form.html.erb
<%= form_with model:@category do |form|  %>
    <%= form.label :name %>
    <%= form.text_field :name %>
    <%= form.submit %>
<% end %>

app/views/categories/edit.html.erb
<h1>Editar Categoría</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1 class="text-2xl font-bold text-teal-500 mt-4 mb-4">Categorías</h1>
<% @categories.each do |category| %>
    <%= link_to category_path(category.id) do %>
        <p class="mb-4 underline"><%= category.name %></p>
    <% end %>
<% end %>

app/views/categories/new.html.erb
<h1>Añadir Categoría</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<h1>Category - <%= @category.name %></h1>
<%= link_to 'Editar Categoría', edit_category_path(@category) %>
<%= link_to 'Eliminar Categoría', category_path(@category), data: {
    turbo_method: :delete,
    turbo_confirm: 'Are you sure?'
} %>