config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  # Consultar rutas: http://127.0.0.1:3000/rails/info/routes
  # Tipo de Petición    Ruta                Controlador(NombreControlador#Método)   Nombre de la Ruta (Helper)
  # get                 '/products/new',    to: 'products#new',                     as: :new_product
  # delete '/products/:id', to: 'products#destroy'
  # patch '/products/:id', to: 'products#update'
  # post '/products', to: 'products#create'
  # get '/products/new', to: 'products#new', as: :new_product
  # get '/products', to: 'products#index'
  # get '/products/:id', to: 'products#show', as: :product
  # get '/products/:id/edit', to: 'products#edit', as: :edit_product

  # Las rutas anteriores pueden ser reemplazadas por esta línea dejando como ruta raíz la página que muestra todos los productos
  # resources crea siete rutas con los verbos HTTP por defecto
  
  namespace :authentication, path: '', as: '' do
    resources :users, only: [:new, :create], path: '/register', path_names: { new: '/' }
    resources :sessions, only: [:new, :create, :destroy], path: '/login', path_names: { new: '/' }
  end

  resources :products, path: '/products'

  get '/categories', to: 'categories#index'
  delete '/categories/:id', to: 'categories#destroy'
  get '/categories/new', to: 'categories#new', as: :new_category
  post '/categories', to: 'categories#create'
  patch '/categories/:id', to: 'categories#update'
  get '/categories/:id', to: 'categories#show', as: :category
  get '/categories/:id/edit', to: 'categories#edit', as: :edit_category

  resources :users, only: :show, path: '/user', param: :username

  resources :favorites, only: [:index, :create, :destroy], param: :product_id

  end

app/models/product.rb
class Product < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :search_full_text, against: {
    title: 'A',
    description: 'B'
  }

  ORDER_BY = {
    newest: "created_at DESC",
    expensive: "price DESC",
    cheapest: "price ASC"
  }

  has_one_attached :photo
  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true

  has_many :favorites, dependent: :destroy

  belongs_to :category
  belongs_to :user, default: -> { Current.user }

  def owner?
    user_id == Current.user&.id
  end

  def broadcast
    broadcast_replace_to self, partial: 'products/product_details', locals: { product: self }
  end

  def favorite!
    favorites.create(user: Current.user)
  end

  def unfavorite!
    favorite.destroy
  end

  def favorite
    favorites.find_by(user: Current.user)
  end
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  skip_before_action :protect_pages, only: [:index, :show]

  def index
    @categories = Category.all.order(name: :asc).load_async
    @pagy, @products = pagy_countless(FindProducts.new.call(product_params_index), limit: 12)
  end

  def show
    # @product = Product.find(params[:id])
    product
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_path, notice: t('.created')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    # @product = Product.find(params[:id])
    # product
    authorize! product
  end

  def update
    # @product = Product.find(params[:id])
    authorize! product
    if product.update(product_params)
      product.broadcast
      redirect_to products_path, notice: t('.updated')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    # @product = Product.find(params[:id])
    authorize! product
    product.destroy
    redirect_to products_path, notice: t('.destroyed'), status: :see_other
  end

  private
    def product_params
      params.require(:product).permit(:title, :description, :price, :photo, :category_id)
    end

    def product_params_index
      params.permit(:category_id, :min_price, :max_price, :query_text, :order_by, :page, :favorites, :user_id)
    end

    def product
      @product ||= Product.find(params[:id])
    end

end

app/views/products/_category.html.erb
<%= link_to products_path(category_id: category.id), class: "bg-white text-gray-600 px-4 py-2 rounded-2xl drop-shadow-sm hover:bg-gray-300" do %>
    <%= category.name %>
<% end %>

app/views/products/_favorite.html.erb
<div id="favorite">
  <% if product.favorite %>
    <%= link_to '💔', favorite_path(product.id), data: {
      turbo_method: :delete
    } %>
  <% else %>
    <%= link_to '💖', favorites_path(product_id: product.id), data: {
      turbo_method: :post
    } %>
  <% end %>
</div>

app/views/products/_form.html.erb
<%= form_with model: @product do |form| %>
  <% @product.errors.full_messages.each do |error| %>
    <div>
      <%= error %>
    </div>
  <% end %>

  <div>
    <%= form.text_field :title, placeholder: "Título", class: "rounded-2xl border-gray-200 mb-4 w-full" %>
  </div>

  <div>
    <%= form.text_area :description, placeholder: "Descripción", class: "rounded-2xl border-gray-200 mb-4 w-full", rows: 5 %>
  </div>

  <div>
    <%= form.number_field :price, placeholder: "Price", class: "rounded-2xl border-gray-200 mb-4 w-full" %>
  </div>

  <div>
    <%= form.collection_select :category_id, Category.all.order(name: :asc), :id, :name, { prompt: "Categoría" }, { class: "rounded-2xl border-gray-200 mb-4 w-full text-gray-500"} %>
  </div>

  <div class="rounded-2xl border-gray-200 mb-4 w-full border-[1px] p-2 text-gray-500">
    <%= form.label :photo %>
    <%= form.file_field :photo %>
  </div>

  <%= form.submit class: "px-4 py-2 font-semibold text-sm bg-cyan-500 text-white rounded-2xl cursor-pointer shadow-sm" %>
<% end %>

app/views/products/_product.html.erb
<%= link_to product_path(product.id), class: 'product bg-white mb-2 rounded sm:w-[calc(33.33333%_-_.5rem)] lg:w-[calc(25%_-_.5rem)]', 'data-turbo-frame': '_top' do %>
<%= image_tag product.photo.attached? ? product.photo : 'placeholder.jpg', class: "w-full h-60 object-cover" %>
  <div class="m-2">
    <span class="font-bold text-xl">$<%= product.price %></span>
    <h2><%= product.title %></h2>
    <p class="text-gray-500 text-sm mt-2"><%= product.description %></p>
  </div>
<% end %>

app/views/products/_product_details.html.erb
<div id="<%= dom_id(product) %>">
  <%= image_tag product.photo, width: 200 if product.photo.attached? %>

  <h1 class='title'><%= product.title %></h1>

  <p class='description'><%= product.description %></p>

  <span class='price'>$<%= product.price %></span>
</div>

app/views/products/edit.html.erb
<%# <h2>Editar Producto</h2> %>
<h2><%= t('.title') %></h2>

<%= render 'form' %>

app/views/products/index.html.erb
<%# <h1>Productos:</h1> %>
<%= turbo_frame_tag 'home' do %>

    <%= form_with url: products_path, method: :get do |form| %>
        <%= form.text_field :query_text, placeholder: 'Buscar Productos...', onChange: 'this.form.requestSubmit()', value: params[:query_text], class: "w-full my-2 rounded-2xl border-gray-200" %>
        <div class="flex">
          <%= form.number_field :min_price, placeholder: 'Precio mínimo', onChange: 'this.form.requestSubmit()', value: params[:min_price], class: "w-1/3 rounded-2xl border-gray-200" %>
          <%= form.number_field :max_price, placeholder: 'Precio máximo', onChange: 'this.form.requestSubmit()', value: params[:max_price], class: "w-1/3 rounded-2xl border-gray-200 mx-2" %>
          <%= form.select :order_by, options_for_select(Product::ORDER_BY.keys.map{ |order| [order] },
              params[:order_by]), {}, { onChange: 'this.form.requestSubmit()', class: "w-1/3 rounded-2xl border-gray-200 text-gray-500" } %>
        </div>
    <% end %>

  <div class="flex overflow-x-scroll gap-2 my-2">
    <%= render(CategoryComponent.new) %>
    <%= render(CategoryComponent.with_collection(@categories)) %>
    <%#= render partial: 'category', collection: @categories %>
  </div>
    <%= turbo_frame_tag :products, class: "flex flex-col m-2" do %>
      <%= turbo_frame_tag "products-#{@pagy.page}", class: 'products flex flex-col w-full sm:flex-row sm:flex-wrap sm:gap-x-2' do %>
          <%= render partial: 'product', collection: @products %>
          <%= turbo_frame_tag "products-#{@pagy.next}", class: 'products flex flex-col w-full sm:flex-row sm:flex-wrap sm:gap-x-2', src: pagy_url_for(@pagy, @pagy.next), loading: :lazy if @pagy.next %>
      <% end %>
    <% end %>
<% end %>

app/views/products/new.html.erb
<%# <h2>Añadir Nuevo Producto</h2> %>
<%= turbo_frame_tag "modal" do %>
  <div data-controller="modal">
    <div data-action="click->modal#close" class="fixed z-10 w-full h-full top-0 left-0 bg-black bg-opacity-40"></div>
    <div data-modal-target="sidebar" class="fixed top-0 right-0 z-20 w-1/2 sm:w-3/6 lg:w-2/6 h-full bg-white overflow-y-scroll shadow flex flex-col ease-in-out duration-300 p-5 translate-x-full">
      <p data-action="click->modal#close">❌</p>
      <h2><%= t('.title') %></h2>
      <%= render 'form' %>
    </div>
  </div>
<% end %>

app/views/products/show.html.erb
<%= javascript_include_tag "turbo", type: "module" %>

<%= render partial: 'products/product_details', locals: { product: @product } %>

<%= link_to 'Editar producto', edit_product_path(@product) if @product.owner? %>

<%= link_to 'Eliminar producto', product_path(@product), data: {
    turbo_method: :delete,
    turbo_confirm: t('common.confirm')
} if @product.owner? %>

<%= link_to "Ver mas productos de #{@product.user.username}", user_path(@product.user.username) %>

<%= render partial: 'favorite', locals: { product: @product } %>

<%= turbo_stream_from @product %>